---
Description:
  Renan Couto / Udacity Capstone
  This script deploys an EC2 Instance with jenkins installed, which
  will be used for Continous Integration (CI) pipeline

Parameters:

  EnvironmentName:
    Description: An environment name that will be prefixed to resouces.
    Type: String

Resources:

  JenkinsSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Jenkins Security Group
      SecurityGroupIngress:
        IpProtocol: tcp
        FromPort: 8080
        ToPort: 8080
        CidrIp: 0.0.0.0/0
      SecurityGroupIngress:
        IpProtocol: tcp
        FromPort: 0
        ToPort: 65535
        CidrIp: 0.0.0.0/0

  JenkinsEC2Instance:
    Type: AWS::EC2::Instance
    Properties: 
      ImageId: ami-0ce21b51cb31a48b8
      KeyName: capstone
      InstanceType: t3.medium
      SecurityGroupIds:
        - !Ref JenkinsSecurityGroup
      BlockDeviceMappings:
      - DeviceName: "/dev/sda1"
        Ebs:
            VolumeSize: '30'
      UserData:
        IyEvYmluL2Jhc2gKZWNobyAiSW5zdGFsbGluZyBKZW5raW5zIgphcHQtZ2V0IHVwZGF0ZQphcHQg
        aW5zdGFsbCAteSBkZWZhdWx0LWpkawp3Z2V0IC1xIC1PIC0gaHR0cHM6Ly9wa2cuamVua2lucy5p
        by9kZWJpYW4vamVua2lucy5pby5rZXkgfCBhcHQta2V5IGFkZCAtCnNoIC1jICdlY2hvIGRlYiBo
        dHRwczovL3BrZy5qZW5raW5zLmlvL2RlYmlhbi1zdGFibGUgYmluYXJ5LyA+IC9ldGMvYXB0L3Nv
        dXJjZXMubGlzdC5kL2plbmtpbnMubGlzdCcKYXB0LWdldCB1cGRhdGUKYXB0LWdldCBpbnN0YWxs
        IC15IGplbmtpbnMKc3lzdGVtY3RsIHN0YXR1cyBqZW5raW5zLnNlcnZpY2UKZWNobyAiSW5zdGFs
        bGluZyBEb2NrZXIiCmFwdC1nZXQgaW5zdGFsbCAteSBcCiAgICAgYXB0LXRyYW5zcG9ydC1odHRw
        cyBcCiAgICAgY2EtY2VydGlmaWNhdGVzIFwKICAgICBjdXJsIFwKICAgICBnbnVwZy1hZ2VudCBc
        CiAgICAgc29mdHdhcmUtcHJvcGVydGllcy1jb21tb24KY3VybCAtZnNTTCBodHRwczovL2Rvd25s
        b2FkLmRvY2tlci5jb20vbGludXgvdWJ1bnR1L2dwZyB8IGFwdC1rZXkgYWRkIC0KYWRkLWFwdC1y
        ZXBvc2l0b3J5IFwKICAgICJkZWIgW2FyY2g9YW1kNjRdIGh0dHBzOi8vZG93bmxvYWQuZG9ja2Vy
        LmNvbS9saW51eC91YnVudHUgXAogICAkKGxzYl9yZWxlYXNlIC1jcykgXAogICBzdGFibGUiCmFw
        dC1nZXQgdXBkYXRlCmFwdC1nZXQgaW5zdGFsbCAteSBkb2NrZXItY2UgZG9ja2VyLWNlLWNsaSBj
        b250YWluZXJkLmlvCnVzZXJtb2QgLWFHIGRvY2tlciB1YnVudHUKZWNobyAiSW5zdGFsbGluZyBM
        aW50ZXIiCmFwdC1nZXQgaW5zdGFsbCAteSB0aWR5Cgo=
      Tags:
        - Key: Name
          Value: !Sub "${EnvironmentName}-JENKINS"